// auth
export const GET_TOKEN = 'GET_TOKEN'
export const LOGOUT = 'LOGOUT'
export const REGISTRATION = 'REGISTRATION'
export const INVITE_CODE_CLIENT = 'INVITE_CODE_CLIENT'
export const RESTORE_PASSWORD = 'RESTORE_PASSWORD'
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD'
export const ACTIVATION_EMAIL = 'ACTIVATION_EMAIL'
export const SING_IN_WITH_GOGGLE = 'SING_IN_WITH_GOGGLE'
export const SING_IN_WITH_FACEBOOK = 'SING_IN_WITH_FACEBOOK'
export const SING_IN_WITH_LDAP = 'SING_IN_WITH_LDAP'
export const CHECK_EMAIL = 'CHECK_EMAIL'

export const GET_SOCIAL = 'GET_SOCIAL'
export const SET_SOCIAL = 'SET_SOCIAL'
// setting
export const GET_LANGUAGE_LIST = 'GET_LANGUAGE_LIST'
export const GET_TRANSLATIONS = 'GET_TRANSLATIONS'
export const GET_CATEGORIES_MENU = 'GET_CATEGORIES_MENU'
export const GET_CATEGORY_FILTERS = 'GET_CATEGORY_FILTERS'

// config
export const GET_CONFIG = 'GET_CONFIG'

// sub
export const GET_SUB_LIST = 'GET_SUB_LIST'
export const CREATE_SUB = 'CREATE_SUB'
export const CANCEL_SUB = 'CANCEL_SUB'
export const GET_CARTS_SUB = 'GET_CARTS_SUB'
export const GET_CART_SUB = 'GET_CART_SUB'

// admin
export const GET_USER_DETAIL = 'GET_USER_DETAIL'
export const EDIT_SETTING = 'EDIT_SETTING'
export const EDIT_PASSWORD = 'EDIT_PASSWORD'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const GET_USER_REFERALS = 'GET_USER_REFERALS'

// home
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES'
export const REQUEST_SEO_TEXT = 'REQUEST_SEO_TEXT'
export const REQUEST_REFERRAL = 'REQUEST_REFERRAL'
export const REQUEST_REFERRAL_PURCHASE = 'REQUEST_REFERRAL_PURCHASE'
export const CHECK_AMOUNT = 'CHECK_AMOUNT'
export const SAVE_REQUEST = 'SAVE_REQUEST'
export const PAYED_REQUEST = 'PAYED_REQUEST'

// catalog
export const REQUEST_CATEGORY_LIST = 'REQUEST_CATEGORY_LIST'
export const REQUEST_CREATE_CATEGORY = 'REQUEST_CREATE_CATEGORY'
export const REQUEST_UPDATE_CATEGORY = 'REQUEST_UPDATE_CATEGORY'
export const DELAY_CATEGORY = 'DELAY_CATEGORY'
export const REQUEST_PRODUCT_LIST = 'REQUEST_PRODUCT_LIST'
export const REQUEST_PRODUCT_LIST_FILTER = 'REQUEST_PRODUCT_LIST_FILTER'
export const DELAY_PRODUCT = 'DELAY_PRODUCT'
export const REQUEST_CREATE_PRODUCT = 'REQUEST_CREATE_PRODUCT'
export const REQUEST_UPDATE_PRODUCT = 'REQUEST_UPDATE_PRODUCT'
export const REQUEST_SAVE_PRODUCT_IMAGE = 'REQUEST_SAVE_PRODUCT_IMAGE'

export const REQUEST_PRODUCT_CATEGORY = 'REQUEST_PRODUCT_CATEGORY'

export const REQUEST_PRODUCT = 'REQUEST_PRODUCT'
export const REQUEST_CATEGORY = 'REQUEST_CATEGORY'
export const REQUEST_CATEGORY_ID = 'REQUEST_CATEGORY_ID'

// cart
export const REQUEST_PRODUCT_CART = 'REQUEST_PRODUCT_CART'
export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART'
export const UPDATE_STATUS_CART = 'UPDATE_STATUS_CART'
export const REQUEST_CREAT_ORDER = 'REQUEST_CREAT_ORDER'
export const REQUEST_DISCOUNT = 'REQUEST_DISCOUNT'

// banners
export const POST_IMPORT_PRODUCTS = 'POST_IMPORT_PRODUCTS'
