// auth
export const REFRESH_TOKEN = 'REFRESH_TOKEN'

export const SET_TOKEN = 'SET_TOKEN'
export const REMOVE_TOKEN = 'REMOVE_TOKEN'
export const SET_LOADING_REGISTRATION = 'SET_LOADING_REGISTRATION'
export const SING_IN_REQUEST_STATUS = 'SING_IN_REQUEST_STATUS'

// settings
export const SET_LANGUAGE_LIST = 'SET_LANGUAGE_LIST'
export const SET_TRANSLATIONS = 'SET_TRANSLATIONS'
export const SET_CATALOG_MENU_LOADING = 'SET_CATALOG_MENU_LOADING'
export const SET_CATALOG_MENU = 'SET_CATALOG_MENU'
export const SET_LIST_CATEGORY_FILTERS = 'SET_LIST_CATEGORY_FILTERS'
export const SET_LIST_CATEGORY_FILTERS_LOADING = 'SET_LIST_CATEGORY_FILTERS_LOADING'

// config
export const GET_CONFIG_LOADING = 'GET_CONFIG_LOADING'
export const SET_CONFIG = 'SET_CONFIG'

// admin
export const SET_USER_BALANCE = 'SET_USER_BALANCE'
export const SET_USER_DETAIL = 'SET_USER_DETAIL'
export const SET_USER_REF_LINK = 'SET_USER_REF_LINK'
export const SET_USER_REFERALS = 'SET_USER_REFERALS'
export const CODE_USER_DETAIL_STATUS = 'CODE_USER_DETAIL_STATUS'

// home
export const SAVE_REQUEST_CATEGORIES = 'SAVE_REQUEST_CATEGORIES'
export const SAVE_REFERRAL = 'SAVE_REFERRAL'
export const REQUEST_AMOUNT = 'REQUEST_AMOUNT'
export const REQUEST_SAVE = 'REQUEST_SAVE'

// cart
export const ADD_TO_CART = 'ADD_TO_CART'
export const REQUEST_REMOVE_PRODUCT_CART = 'REQUEST_REMOVE_PRODUCT_CART'
export const INCREASE_PRODUCT_CART_COUNT = 'INCREASE_PRODUCT_CART_COUNT'
export const DECREASE_PRODUCT_CART_COUNT = 'DECREASE_PRODUCT_CART_COUNT'
export const UPDATE_PRODUCT_CART_COUNT = 'UPDATE_PRODUCT_CART_COUNT'
export const REQUEST_UPDATE_STATUS_CART = 'REQUEST_UPDATE_STATUS_CART'
export const CLEAR_CART = 'CLEAR_CART'
export const UPDATE_ID_ORDER = 'UPDATE_ID_ORDER'

// banners
export const SAVE_REQUEST_BANNERS = 'SAVE_REQUEST_BANNERS'
